### ISSUE TITLE
error "no module named pysticktim"

### ISSUE THREAD

**Issue by dmalawey** [ansarid/pysicktim#1] opened 2019-10-28 21:38 UTC
I installed pyusb and pysicktim, but L1_lidar.py still has an error.   See output:

```
----------------------------------------
  Failed building wheel for pyusb
  Running setup.py clean for pyusb
Failed to build pyusb
Installing collected packages: pyusb
  Running setup.py install for pyusb ... done
Successfully installed pyusb-1.0.2
debian@beaglebone:~/basics$ pip3 install pysicktim
Collecting pysicktim
  Using cached https://files.pythonhosted.org/packages/d9/13/7659e483922f9a249cc7e183b50572ed5bdfb8b66b02718d892a73c9a3dc/pysicktim-0.0.9.tar.gz
Building wheels for collected packages: pysicktim
  Running setup.py bdist_wheel for pysicktim ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5gt2cof6/pysicktim/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqflwdpmopip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for pysicktim
  Running setup.py clean for pysicktim
Failed to build pysicktim
Installing collected packages: pysicktim
  Running setup.py install for pysicktim ... done
Successfully installed pysicktim-0.0.9
debian@beaglebone:~/basics$ sudo python3 L1_lidar.py
sudo: unable to resolve host beaglebone
Traceback (most recent call last):
  File "L1_lidar.py", line 7, in <module>
    import pysicktim as lidar # required for communication with TiM561 lidar sensor
ImportError: No module named 'pysicktim'
debian@beaglebone:~/basics$
```

**Comment by ansarid** [comment] 2019-10-28 22:00
@dmalawey please include the command you ran with the output. Try running pip3 with sudo

**Comment by ansarid** [comment] 2019-10-29 17:46
@dmalawey were you able to resolve this issue? If not please let me know. If so I can close this issue.

**Comment by ansarid** [comment] 2019-10-30 19:57
Closing because of no response. Assuming the issue is solved. If not please let me know and I will reopen this issue.

**Closed as completed by ansarid** 2019-10-30 19:57 UTC
